// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	slog "log/slog"
)

// LogHandler is an autogenerated mock type for the LogHandler type
type LogHandler struct {
	mock.Mock
}

type LogHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *LogHandler) EXPECT() *LogHandler_Expecter {
	return &LogHandler_Expecter{mock: &_m.Mock}
}

// Enabled provides a mock function with given fields: _a0, _a1
func (_m *LogHandler) Enabled(_a0 context.Context, _a1 slog.Level) bool {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Enabled")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, slog.Level) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// LogHandler_Enabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enabled'
type LogHandler_Enabled_Call struct {
	*mock.Call
}

// Enabled is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 slog.Level
func (_e *LogHandler_Expecter) Enabled(_a0 interface{}, _a1 interface{}) *LogHandler_Enabled_Call {
	return &LogHandler_Enabled_Call{Call: _e.mock.On("Enabled", _a0, _a1)}
}

func (_c *LogHandler_Enabled_Call) Run(run func(_a0 context.Context, _a1 slog.Level)) *LogHandler_Enabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(slog.Level))
	})
	return _c
}

func (_c *LogHandler_Enabled_Call) Return(_a0 bool) *LogHandler_Enabled_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LogHandler_Enabled_Call) RunAndReturn(run func(context.Context, slog.Level) bool) *LogHandler_Enabled_Call {
	_c.Call.Return(run)
	return _c
}

// Handle provides a mock function with given fields: _a0, _a1
func (_m *LogHandler) Handle(_a0 context.Context, _a1 slog.Record) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, slog.Record) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LogHandler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type LogHandler_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 slog.Record
func (_e *LogHandler_Expecter) Handle(_a0 interface{}, _a1 interface{}) *LogHandler_Handle_Call {
	return &LogHandler_Handle_Call{Call: _e.mock.On("Handle", _a0, _a1)}
}

func (_c *LogHandler_Handle_Call) Run(run func(_a0 context.Context, _a1 slog.Record)) *LogHandler_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(slog.Record))
	})
	return _c
}

func (_c *LogHandler_Handle_Call) Return(_a0 error) *LogHandler_Handle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LogHandler_Handle_Call) RunAndReturn(run func(context.Context, slog.Record) error) *LogHandler_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// WithAttrs provides a mock function with given fields: attrs
func (_m *LogHandler) WithAttrs(attrs []slog.Attr) slog.Handler {
	ret := _m.Called(attrs)

	if len(ret) == 0 {
		panic("no return value specified for WithAttrs")
	}

	var r0 slog.Handler
	if rf, ok := ret.Get(0).(func([]slog.Attr) slog.Handler); ok {
		r0 = rf(attrs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(slog.Handler)
		}
	}

	return r0
}

// LogHandler_WithAttrs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithAttrs'
type LogHandler_WithAttrs_Call struct {
	*mock.Call
}

// WithAttrs is a helper method to define mock.On call
//   - attrs []slog.Attr
func (_e *LogHandler_Expecter) WithAttrs(attrs interface{}) *LogHandler_WithAttrs_Call {
	return &LogHandler_WithAttrs_Call{Call: _e.mock.On("WithAttrs", attrs)}
}

func (_c *LogHandler_WithAttrs_Call) Run(run func(attrs []slog.Attr)) *LogHandler_WithAttrs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]slog.Attr))
	})
	return _c
}

func (_c *LogHandler_WithAttrs_Call) Return(_a0 slog.Handler) *LogHandler_WithAttrs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LogHandler_WithAttrs_Call) RunAndReturn(run func([]slog.Attr) slog.Handler) *LogHandler_WithAttrs_Call {
	_c.Call.Return(run)
	return _c
}

// WithGroup provides a mock function with given fields: name
func (_m *LogHandler) WithGroup(name string) slog.Handler {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for WithGroup")
	}

	var r0 slog.Handler
	if rf, ok := ret.Get(0).(func(string) slog.Handler); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(slog.Handler)
		}
	}

	return r0
}

// LogHandler_WithGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithGroup'
type LogHandler_WithGroup_Call struct {
	*mock.Call
}

// WithGroup is a helper method to define mock.On call
//   - name string
func (_e *LogHandler_Expecter) WithGroup(name interface{}) *LogHandler_WithGroup_Call {
	return &LogHandler_WithGroup_Call{Call: _e.mock.On("WithGroup", name)}
}

func (_c *LogHandler_WithGroup_Call) Run(run func(name string)) *LogHandler_WithGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *LogHandler_WithGroup_Call) Return(_a0 slog.Handler) *LogHandler_WithGroup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LogHandler_WithGroup_Call) RunAndReturn(run func(string) slog.Handler) *LogHandler_WithGroup_Call {
	_c.Call.Return(run)
	return _c
}

// NewLogHandler creates a new instance of LogHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLogHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *LogHandler {
	mock := &LogHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
